id = "ashen"
name = "Ashen"
version = "1.0.0"
schema_version = 1
authors = ["Adhi Thirumala <me@adhithirumala.com>"]
description = "A dark, warm, muted color scheme. Now on Zed!"
repository = "https://github.com/adhi-thirumala/ashen.zed"
